name             'TiCo'
maintainer       'fashion4home'
maintainer_email 'dj@rebel-l.net'
license          'All rights reserved'
description      'Installs/Configures TiCo'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '2.1.0'
depends          'Cups'
depends          'Fop'
depends          'Nginx'
depends          'NodeJs'
depends          'Php'
depends          'Projects'
depends          'System'
